/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SellRouteImport } from './routes/sell'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as CompanyIndustryIdRouteImport } from './routes/company.$industryId'
import { Route as MaterialMaterialIdRouteImport } from './routes/material.$materialId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndustryIdRoute = CompanyIndustryIdRouteImport.update({
  id: '/company/$industryId',
  path: '/company/$industryId',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialMaterialIdRoute = MaterialMaterialIdRouteImport.update({
  id: '/material/$materialId',
  path: '/material/$materialId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/transactions': typeof TransactionsRoute
  '/company/$industryId': typeof CompanyIndustryIdRoute
  '/material/$materialId': typeof MaterialMaterialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/transactions': typeof TransactionsRoute
  '/company/$industryId': typeof CompanyIndustryIdRoute
  '/material/$materialId': typeof MaterialMaterialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sell': typeof SellRoute
  '/transactions': typeof TransactionsRoute
  '/company/$industryId': typeof CompanyIndustryIdRoute
  '/material/$materialId': typeof MaterialMaterialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buy'
    | '/login'
    | '/profile'
    | '/register'
    | '/sell'
    | '/transactions'
    | '/company/$industryId'
    | '/material/$materialId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buy'
    | '/login'
    | '/profile'
    | '/register'
    | '/sell'
    | '/transactions'
    | '/company/$industryId'
    | '/material/$materialId'
  id:
    | '__root__'
    | '/'
    | '/buy'
    | '/login'
    | '/profile'
    | '/register'
    | '/sell'
    | '/transactions'
    | '/company/$industryId'
    | '/material/$materialId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyRoute: typeof BuyRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SellRoute: typeof SellRoute
  TransactionsRoute: typeof TransactionsRoute
  CompanyIndustryIdRoute: typeof CompanyIndustryIdRoute
  MaterialMaterialIdRoute: typeof MaterialMaterialIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$industryId': {
      id: '/company/$industryId'
      path: '/company/$industryId'
      fullPath: '/company/$industryId'
      preLoaderRoute: typeof CompanyIndustryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$materialId': {
      id: '/material/$materialId'
      path: '/material/$materialId'
      fullPath: '/material/$materialId'
      preLoaderRoute: typeof MaterialMaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyRoute: BuyRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SellRoute: SellRoute,
  TransactionsRoute: TransactionsRoute,
  CompanyIndustryIdRoute: CompanyIndustryIdRoute,
  MaterialMaterialIdRoute: MaterialMaterialIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
